name: Android Build

on: pull_request

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Build project
        run: ./gradlew :app:assembleRceDebug

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Lint
        run: ./gradlew :app:lintRceRelease :common:lintRceRelease :data:lintRceRelease :domain:lintRceRelease :presentation:lintRceRelease

      - name: Upload lint reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Lint
          path: |
            app/build/reports/lint
            common/build/reports/lint
            data/build/reports/lint
            domain/build/reports/lint
            presentation/build/reports/lint
          retention-days: 1

  detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Detekt
        run: ./gradlew detekt

      - name: Upload detekt reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Detekt
          path: |
            app/build/reports/detekt
            common/build/reports/detekt
            data/build/reports/detekt
            domain/build/reports/detekt
            presentation/build/reports/detekt
          retention-days: 1

  spotbugs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: gradle

      - name: Spotbugs
        run: ./gradlew spotbugsRceDebug

      - name: Upload spotbugs reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: Spotbugs
          path: |
            app/build/reports/spotbugs
            common/build/reports/spotbugs
            data/build/reports/spotbugs
            domain/build/reports/spotbugs
            presentation/build/reports/spotbugs
          retention-days: 1